# appspec.yml 

version: 0.0 
os: linux 
files: 
  - source: / 
    destination: /home/ec2-user/step2/ 
    overwrite: yes 

permissions: 
  - object: / 
    pattern: "**" 
    owner: ec2-user 
    group: ec2-user
